config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'home_page#index'
  resources :home_page
  resources :recipes

  get 'recipes/index'


  post 'users/new'
 
  post 'users/login', to:"users#login"



  get 'search', to:"recipes#search"


end

app/models/recipe.rb
class Recipe
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :ingredients, type: String
  field :steps, type: String
  field :creator, type: String



end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  field :username, type: String
  field :password, type: String
  field :profilePicture, type: String
  field :likedRecipes, type: String
  field :createdRecipes, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  skip_before_action :verify_authenticity_token
    def index
        @recipes = Recipe.all
    end

    def show
        @recipes = Recipe.all
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/new
  def new

  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    # render plain: params[:recipe].inspect
    @recipe = Recipe.new(recipe_params)

    @recipe.save
    redirect_to "/home_page"
  end

  private def recipe_params
    params.require(:require).permit(:name, :ingredients, :steps)
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
      @recipes = Recipe.any_of({name: /#{params[:q]}/i}, {ingredients: /#{params[:q]}/i})
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :ingredients, :steps)
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ edit update destroy ]
  skip_before_action :verify_authenticity_token



  # GET /users or /users.json
  def index
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new

  end

  # POST /users/login
  def login
    @user = User.new(user_params)

    if User.exists?("username": @user.username, "password": @user.password)
        print "\n\n\n\n\nSIGNED IN!!!\n\n\n\n\n"
        redirect_to home_page_index_path
    else
      flash.notice = "Invalid login."
      redirect_to users_login_path
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    puts "Created a user"

    if !User.exists?("username": user_params[:username])
        @user = User.new
        @user.username =  user_params[:username]
        @user.password = user_params[:password]
        @pic = params[:user][:profilePicture]


        if (@pic != nil)
          File.open(Rails.root.join("public","images", @pic.original_filename), 'wb') do |file|
            file.write(@pic.read)
          end
          @user.profilePicture = (params[:user][:profilePicture].original_filename)
          else
          @user.profilePicture = "public/images/defaultPfp.png"
        end
        @user.save
        redirect_to users_login_path #recipes_path
    else
      flash.notice = "Username is taken."
      redirect_to new_user_path

    end


  end

  private def user_params
    params.require(:require).permit(:username, :password, :profilePicture)
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home_page/index.html.erb
<!--This file is the home page file. It has all of the style declarations for how the recipes
    are displayed. In addition, it sets the definition for the header that is shown.-->

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrollable Menu</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f0f0f0;
    }
    .top-bar {
      background-color: #333;
      color: #fff;
      padding: 10px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .search-bar {
      background-color: #fff;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
      width: 80%;
      display: flex;
    }
    .search-input {
      flex: 1;
      border: none;
      outline: none;
      font-size: 14px;
    }
    .search-icon {
      width: 20px;
      height: 20px;
      margin-right: 5px;
    }

    .menu {
       background-color: #fff;
       padding: 20px;
       border: 1px solid #ccc;
       border-radius: 5px;
       height: 300px; /* Adjust the height as needed */
       overflow-y: scroll;
    }

    .menu-item {
       padding: 10px;
       border-bottom: 1px solid #ccc;
    }

    .pagination {
       margin-top: 10px;
       text-align: center;
    }

    .page-link {
       text-decoration: none;
       padding: 5px 10px;
       border: 1px solid #ccc;
       border-radius: 3px;
       margin: 5px;
       color: #333;
       background-color: #eee;
    }
    </style>
</head>

<body>
  <div class="top-bar">
    <!--Shows the user icon in top left-->
    <%= link_to(image_tag("R.png", size: "40x40", :alt => "search-icon"), home_page_index_path) %>
        <form class="form-inline my-2 my-lg-0" action="/search">
           <input class="form-control mr-sm-2" name="q" type = "text" placeholder="Search" ari-label="Search">
        </form>


    <div class="recipe-button">
      <!--Shows the two links in top right.
          The first link takes you to the signin. The second one takes you to create a new recipe.-->
       <ul class="nav navbar-nav">
         <li><%= link_to "Sign In/Create Account", users_login_path  %></li>
         <li><%= link_to "Create Recipe", new_recipe_path %></li>
       </ul>
    </div>
  </div>
    
  <table class="ui fixed single line sortable celled table">
     <thead>
        <tr>
           <th>Recipe</th>
              <th>Ingredients</th>
              <th>Steps</th>
              <th class="descending">Created When</th>
        </tr>
     </thead>
     <tbody>
       <% @recipes.each do |recipe| %>
       <tr>
         <td><%= link_to recipe.name, recipe %></td>
         <td><%= recipe.ingredients %></td>
         <td><%= recipe.steps %></td>
         <td><%= time_ago_in_words(recipe.created_at) %> ago</td>
       <tr>
       <% end %>
     </tbody>
   </table>
</body>

app/views/recipe/index.html.erb
<h1>Recipe#index</h1>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">


</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "Sign In/Create Account", users_login_path %><br>
<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrollable Menu</title>
  <style>
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background-color: #f0f0f0;
      }
      .top-bar {
          background-color: #333;
          color: #fff;
          padding: 10px;
          display: flex;
          justify-content: space-between;
          align-items: center;
      }
      .search-bar {
          background-color: #fff;
          padding: 10px;
          border: 1px solid #ccc;
          border-radius: 5px;
          width: 80%;
          display: flex;
      }
      .search-input {
          flex: 1;
          border: none;
          outline: none;
          font-size: 14px;
      }
      .search-icon {
          width: 20px;
          height: 20px;
          margin-right: 5px;
      }

      .menu {
          background-color: #fff;
          padding: 20px;
          border: 1px solid #ccc;
          border-radius: 5px;
          height: 300px; /* Adjust the height as needed */
          overflow-y: scroll;
      }

      .menu-item {
          padding: 10px;
          border-bottom: 1px solid #ccc;
      }

      .pagination {
          margin-top: 10px;
          text-align: center;
      }

      .page-link {
          text-decoration: none;
          padding: 5px 10px;
          border: 1px solid #ccc;
          border-radius: 3px;
          margin: 5px;
          color: #333;
          background-color: #eee;
      }
  </style>
</head>
<body>
<div class="top-bar">
  <%= link_to(image_tag("R.png", size: "40x40", :alt => "search-icon"), home_page_index_path) %>
  <form class="form-inline my-2 my-lg-0" action="/search">
    <input class="form-control mr-sm-2" name="q" type = "text" placeholder="Search" ari-label="Search">
  </form>

  <% if false %>
    <div class="account-button">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Account", show_user_path %></li>
      </ul>
    </div>
  <% end %>

  <div class="recipe-button">
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign In/Create Account", users_login_path  %></li>
      <li><%= link_to "Create Recipe", new_recipe_path %></li>
    </ul>
  </div>
</div>
<h1> Add Recipe </h1>
<%= form_for :recipe, url: recipes_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </p>

  <p>
    <%= f.label :steps %><br>
    <%= f.text_area :steps %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/recipes/search.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrollable Menu</title>
  <style>
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background-color: #f0f0f0;
      }
      .top-bar {
          background-color: #333;
          color: #fff;
          padding: 10px;
          display: flex;
          justify-content: space-between;
          align-items: center;
      }
      .search-bar {
          background-color: #fff;
          padding: 10px;
          border: 1px solid #ccc;
          border-radius: 5px;
          width: 80%;
          display: flex;
      }
      .search-input {
          flex: 1;
          border: none;
          outline: none;
          font-size: 14px;
      }
      .search-icon {
          width: 20px;
          height: 20px;
          margin-right: 5px;
      }

      .menu {
          background-color: #fff;
          padding: 20px;
          border: 1px solid #ccc;
          border-radius: 5px;
          height: 300px; /* Adjust the height as needed */
          overflow-y: scroll;
      }

      .menu-item {
          padding: 10px;
          border-bottom: 1px solid #ccc;
      }

      .pagination {
          margin-top: 10px;
          text-align: center;
      }

      .page-link {
          text-decoration: none;
          padding: 5px 10px;
          border: 1px solid #ccc;
          border-radius: 3px;
          margin: 5px;
          color: #333;
          background-color: #eee;
      }
  </style>
</head>
<body>
<div class="top-bar">
  <%= link_to(image_tag("R.png", size: "40x40", :alt => "search-icon"), home_page_index_path) %>
  <form class="form-inline my-2 my-lg-0" action="/search">
    <input class="form-control mr-sm-2" name="q" type = "text" placeholder="Search" aria-label="Search">
  </form>

  <% if false %>
    <div class="account-button">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Account", show_user_path %></li>
      </ul>
    </div>
  <% end %>

  <div class="recipe-button">
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign In/Create Account", users_login_path  %></li>
      <li><%= link_to "Create Recipe", new_recipe_path %></li>
    </ul>
  </div>
</div>
<table class="ui fixed single line sortable celled table">
  <thead>
  <h1>Search Results</h1>
  <tr>
    <th>Recipe</th>
    <th>Ingredients</th>
    <th>Steps</th>
    <th class="descending">Created When</th>
  </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
  <tr>
    <td><%= link_to recipe.name, recipe %></td>
    <td><%= recipe.ingredients %></td>
    <td><%= recipe.steps %></td>
    <td><%= time_ago_in_words(recipe.created_at) %> ago</td>
  </tr>
  <% end %>
  </tbody>
</table>
</body>

app/views/recipes/show.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrollable Menu</title>
  <style>
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background-color: #f0f0f0;
      }
      .top-bar {
          background-color: #333;
          color: #fff;
          padding: 10px;
          display: flex;
          justify-content: space-between;
          align-items: center;
      }
      .search-bar {
          background-color: #fff;
          padding: 10px;
          border: 1px solid #ccc;
          border-radius: 5px;
          width: 80%;
          display: flex;
      }
      .search-input {
          flex: 1;
          border: none;
          outline: none;
          font-size: 14px;
      }
      .search-icon {
          width: 20px;
          height: 20px;
          margin-right: 5px;
      }

      .menu {
          background-color: #fff;
          padding: 20px;
          border: 1px solid #ccc;
          border-radius: 5px;
          height: 300px; /* Adjust the height as needed */
          overflow-y: scroll;
      }

      .menu-item {
          padding: 10px;
          border-bottom: 1px solid #ccc;
      }

      .pagination {
          margin-top: 10px;
          text-align: center;
      }

      .page-link {
          text-decoration: none;
          padding: 5px 10px;
          border: 1px solid #ccc;
          border-radius: 3px;
          margin: 5px;
          color: #333;
          background-color: #eee;
      }
  </style>
</head>
<body>
<div class="top-bar">
  <%= link_to(image_tag("R.png", size: "40x40", :alt => "search-icon"), home_page_index_path) %>
  <form class="form-inline my-2 my-lg-0" action="/search">
    <input class="form-control mr-sm-2" name="q" type = "text" placeholder="Search" ari-label="Search">
  </form>

  <% if false %>
    <div class="account-button">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Account", show_user_path %></li>
      </ul>
    </div>
  <% end %>

  <div class="recipe-button">
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign In/Create Account", users_login_path  %></li>
      <li><%= link_to "Create Recipe", new_recipe_path %></li>
    </ul>
  </div>
</div>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Steps:</strong>
  <%= @recipe.steps %>

</p>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to home", home_page_index_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrollable Menu</title>
  <style>
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background-color: #f0f0f0;
      }
      .top-bar {
          background-color: #333;
          color: #fff;
          padding: 10px;
          display: flex;
          justify-content: space-between;
          align-items: center;
      }
      .search-bar {
          background-color: #fff;
          padding: 10px;
          border: 1px solid #ccc;
          border-radius: 5px;
          width: 80%;
          display: flex;
      }
      .search-input {
          flex: 1;
          border: none;
          outline: none;
          font-size: 14px;
      }
      .search-icon {
          width: 20px;
          height: 20px;
          margin-right: 5px;
      }

      .menu {
          background-color: #fff;
          padding: 20px;
          border: 1px solid #ccc;
          border-radius: 5px;
          height: 300px; /* Adjust the height as needed */
          overflow-y: scroll;
      }

      .menu-item {
          padding: 10px;
          border-bottom: 1px solid #ccc;
      }

      .pagination {
          margin-top: 10px;
          text-align: center;
      }

      .page-link {
          text-decoration: none;
          padding: 5px 10px;
          border: 1px solid #ccc;
          border-radius: 3px;
          margin: 5px;
          color: #333;
          background-color: #eee;
      }
  </style>
</head>
<body>
<div class="top-bar">
  <%= link_to(image_tag("R.png", size: "40x40", :alt => "search-icon"), home_page_index_path) %>
  <form class="form-inline my-2 my-lg-0" action="/search">
    <input class="form-control mr-sm-2" name="q" type = "text" placeholder="Search" ari-label="Search">
  </form>

  <% if false %>
    <div class="account-button">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Account", show_user_path %></li>
      </ul>
    </div>
  <% end %>

  <div class="recipe-button">
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign In/Create Account", users_login_path  %></li>
      <li><%= link_to "Create Recipe", new_recipe_path %></li>
    </ul>
  </div>
</div>
<h1> Sign in </h1>

<%= form_for :user do |f| %>
  <p>
    <%= f.label :Username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :Password %><br>
    <%= f.password_field :password %>
  </p>


  <%= f.submit "Sign in" %>
  <%= link_to "Create Account", new_user_path %>

<% end %>

app/views/users/login.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrollable Menu</title>
  <style>
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background-color: #f0f0f0;
      }
      .top-bar {
          background-color: #333;
          color: #fff;
          padding: 10px;
          display: flex;
          justify-content: space-between;
          align-items: center;
      }
      .search-bar {
          background-color: #fff;
          padding: 10px;
          border: 1px solid #ccc;
          border-radius: 5px;
          width: 80%;
          display: flex;
      }
      .search-input {
          flex: 1;
          border: none;
          outline: none;
          font-size: 14px;
      }
      .search-icon {
          width: 20px;
          height: 20px;
          margin-right: 5px;
      }

      .menu {
          background-color: #fff;
          padding: 20px;
          border: 1px solid #ccc;
          border-radius: 5px;
          height: 300px; /* Adjust the height as needed */
          overflow-y: scroll;
      }

      .menu-item {
          padding: 10px;
          border-bottom: 1px solid #ccc;
      }

      .pagination {
          margin-top: 10px;
          text-align: center;
      }

      .page-link {
          text-decoration: none;
          padding: 5px 10px;
          border: 1px solid #ccc;
          border-radius: 3px;
          margin: 5px;
          color: #333;
          background-color: #eee;
      }
  </style>
</head>
<body>
<div class="top-bar">
  <%= link_to(image_tag("R.png", size: "40x40", :alt => "search-icon"), home_page_index_path) %>
  <form class="form-inline my-2 my-lg-0" action="/search">
    <input class="form-control mr-sm-2" name="q" type = "text" placeholder="Search" ari-label="Search">
  </form>

  <% if false %>
    <div class="account-button">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Account", show_user_path %></li>
      </ul>
    </div>
  <% end %>

  <div class="recipe-button">
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign In/Create Account", users_login_path  %></li>
      <li><%= link_to "Create Recipe", new_recipe_path %></li>
    </ul>
  </div>
</div>

<h1> Sign in </h1>

<%= form_for :user do |f| %>
  <p>
    <%= f.label :Username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :Password %><br>
    <%= f.password_field :password %>
  </p>


  <%= f.submit "Sign in" %>
  <%= link_to "Create Account", new_user_path %>

<% end %>

app/views/users/new.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrollable Menu</title>
  <style>
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background-color: #f0f0f0;
      }
      .top-bar {
          background-color: #333;
          color: #fff;
          padding: 10px;
          display: flex;
          justify-content: space-between;
          align-items: center;
      }
      .search-bar {
          background-color: #fff;
          padding: 10px;
          border: 1px solid #ccc;
          border-radius: 5px;
          width: 80%;
          display: flex;
      }
      .search-input {
          flex: 1;
          border: none;
          outline: none;
          font-size: 14px;
      }
      .search-icon {
          width: 20px;
          height: 20px;
          margin-right: 5px;
      }

      .menu {
          background-color: #fff;
          padding: 20px;
          border: 1px solid #ccc;
          border-radius: 5px;
          height: 300px; /* Adjust the height as needed */
          overflow-y: scroll;
      }

      .menu-item {
          padding: 10px;
          border-bottom: 1px solid #ccc;
      }

      .pagination {
          margin-top: 10px;
          text-align: center;
      }

      .page-link {
          text-decoration: none;
          padding: 5px 10px;
          border: 1px solid #ccc;
          border-radius: 3px;
          margin: 5px;
          color: #333;
          background-color: #eee;
      }
  </style>
</head>
<body>
<div class="top-bar">
  <%= link_to(image_tag("R.png", size: "40x40", :alt => "search-icon"), home_page_index_path) %>
  <form class="form-inline my-2 my-lg-0" action="/search">
    <input class="form-control mr-sm-2" name="q" type = "text" placeholder="Search" ari-label="Search">
  </form>

  <% if false %>
    <div class="account-button">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Account", show_user_path %></li>
      </ul>
    </div>
  <% end %>

  <div class="recipe-button">
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign In/Create Account", users_login_path  %></li>
      <li><%= link_to "Create Recipe", new_recipe_path %></li>
    </ul>
  </div>
</div>
<h1> Create Account </h1>
<%= form_for :user, url: users_path  do |f| %>
  <p>
    <%= f.label :User_Name %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :Profile_Picture %><br>
    <%= f.file_field :profilePicture %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/show.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrollable Menu</title>
  <style>
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 0;
          background-color: #f0f0f0;
      }
      .top-bar {
          background-color: #333;
          color: #fff;
          padding: 10px;
          display: flex;
          justify-content: space-between;
          align-items: center;
      }
      .search-bar {
          background-color: #fff;
          padding: 10px;
          border: 1px solid #ccc;
          border-radius: 5px;
          width: 80%;
          display: flex;
      }
      .search-input {
          flex: 1;
          border: none;
          outline: none;
          font-size: 14px;
      }
      .search-icon {
          width: 20px;
          height: 20px;
          margin-right: 5px;
      }

      .menu {
          background-color: #fff;
          padding: 20px;
          border: 1px solid #ccc;
          border-radius: 5px;
          height: 300px; /* Adjust the height as needed */
          overflow-y: scroll;
      }

      .menu-item {
          padding: 10px;
          border-bottom: 1px solid #ccc;
      }

      .pagination {
          margin-top: 10px;
          text-align: center;
      }

      .page-link {
          text-decoration: none;
          padding: 5px 10px;
          border: 1px solid #ccc;
          border-radius: 3px;
          margin: 5px;
          color: #333;
          background-color: #eee;
      }
  </style>
</head>
<body>
<div class="top-bar">
  <%= link_to(image_tag("R.png", size: "40x40", :alt => "search-icon"), home_page_index_path) %>
  <form class="form-inline my-2 my-lg-0" action="/search">
    <input class="form-control mr-sm-2" name="q" type = "text" placeholder="Search" ari-label="Search">
  </form>

  <% if false %>
    <div class="account-button">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Account", show_user_path %></li>
      </ul>
    </div>
  <% end %>

  <div class="recipe-button">
    <ul class="nav navbar-nav">
      <li><%= link_to "Sign In/Create Account", users_login_path  %></li>
      <li><%= link_to "Create Recipe", new_recipe_path %></li>
    </ul>
  </div>
</div>

<h1> Sign in </h1>

<%= form_for :user do |f| %>
  <p>
    <%= f.label :Username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :Password %><br>
    <%= f.password_field :password %>
  </p>


  <%= f.submit "Sign in" %>
  <%= link_to "Create Account", new_user_path %>

<% end %>